pipeline{
    agent any

    stages{
        stage("Deploy"){
            steps{
                sh '''
                    oc project dievia-deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
